nelmio_cors:
  defaults:
    allow_origin: ['%env(FRONTEND_URL)%']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/': ~
    '^/user': ~